### ISSUE TITLE
Wonky Power Gain with Overwhelming 

### ISSUE THREAD

**Issue by Volkmar77** [Aliharu/Foundry-ExEss#1]
Occasionally, overwhelming seems to ADD to power gained, instead of substituting it. 
This seems to happen if the power gained from an attack is less than the overwhelming value of the weapon.
The expected outcome is that the OV is the power you gain, if the attack generates less, not that it adds to it.

Example: a withering attack with an OV 2 weapon generates 1 power (base success, no extra successes over Defense), the combat box generated said the attacker got 3 power instead of 2. Also if the attack would generate 2 power (base success, 1 extra success) the box says 3 power gained

![image](https://user-images.githubusercontent.com/94173379/141458679-067f27bb-1af8-4cce-8b54-bb33c69cd27b.png)

**Comment by Aliharu** [comment]
So, this is a rules thing but i'm pretty sure OVW does not include the Base Power.  So if you have 2 OVW and you hit you gain 1 for hitting +2 OVW for 3 Power

**Comment by Volkmar77** [comment]
There has just been a discussion on the OPP discord about it. The situation is quite confusing, because one part of the book says something really complex (the combat section), while the panoply says something really simple (OVW is the minimum power generated by an attack), but it seems to me the consensus is to go with what the panoply says, ie. Overwhelming is the minimum power you can gain on an attack. I guess we need to wait for the full book to know for sure :P
