### ISSUE TITLE
No Attribute names

### ISSUE THREAD

**Issue by CrackedRemy** [Aliharu/Foundry-ExEss#10]
![Untitled](https://github.com/Aliharu/Foundry-ExEss/assets/138330670/b5227d2a-843b-4f46-a4bd-5c7943ea172c)
The 3 attributes are not labeled with Force, Finesse, and Fortitude

**Comment by Aliharu** [comment]
Should be fixed with 1.4.1

**Comment by CrackedRemy** [comment]
Thank you!
